version: "3"

services:
  backend:
    build: backend
    restart: always
    ports:
      - 8088:8088
      - 5678:5678
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - app_network
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./backend:/fastapi

  frontend:
    build: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 8501:8501
    networks:
      - app_network
    container_name: frontend
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./frontend:/streamlit

networks:
  app_network:
    driver: bridge

volumes:
  data:
    name: data